### ISSUE TITLE
v1.10.0 throws "To is not a function"

### ISSUE THREAD

**Issue by sorioinc** [SalesforceCommerceCloud/commerce-sdk-isomorphic#122]
Hi all,

I'm facing a problem with the v1.10.0, it is throwing:
```
TypeError: To is not a function
    at eval (webpack-internal:///./node_modules/commerce-sdk-isomorphic/lib/index.esm.js:19:227343)
    at di (webpack-internal:///./node_modules/commerce-sdk-isomorphic/lib/index.esm.js:19:21359)
    at Generator.eval [as _invoke] (webpack-internal:///./node_modules/commerce-sdk-isomorphic/lib/index.esm.js:19:21109)
    at Generator.Ii.forEach.e.<computed> [as next] (webpack-internal:///./node_modules/commerce-sdk-isomorphic/lib/index.esm.js:19:21733)
    at Kn (webpack-internal:///./node_modules/commerce-sdk-isomorphic/lib/index.esm.js:19:19318)
    at o (webpack-internal:///./node_modules/commerce-sdk-isomorphic/lib/index.esm.js:19:19522)
    at eval (webpack-internal:///./node_modules/commerce-sdk-isomorphic/lib/index.esm.js:19:19583)
    at new Promise (<anonymous>)
    at eval (webpack-internal:///./node_modules/commerce-sdk-isomorphic/lib/index.esm.js:19:19462)
    at eval (webpack-internal:///./node_modules/commerce-sdk-isomorphic/lib/index.esm.js:19:227606)
    at eval (webpack-internal:///./app/commerce-api/index.js:171:35)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
### Steps to reproduce:

1. Fresh install retail app using `pwa-kit-create-app`
2. Remove `package-lock.json`
3. Remove `node_modules` directory
4. Run `npm i`
5. Run `npm start`

A workaround is to lock the version specifically to `1.9.0`

**Comment by tarcang** [comment]
Thank you @sorioinc for raising the issue, I am working to fix this.

**Comment by tarcang** [comment]
Hello @sorioinc , please consume the v1.10.1 patch version that fixes this bug. https://www.npmjs.com/package/commerce-sdk-isomorphic
