### ISSUE TITLE
yarn run renderTemplates throwing error

### ISSUE THREAD

**Issue by saqibcloudconversion** [SalesforceCommerceCloud/commerce-sdk-isomorphic#46]
My node v is 12.22.1
yarn version is v 1.21.1
After Yarn Install, I tried to run the rendertemplates command as suggested in documentation. 

`yarn run renderTemplates
yarn run v1.21.1
$ ts-node --compiler-options '{"module": "commonjs", "target": "ES6" }' generate.ts
undefined:1
'{module:
^

SyntaxError: Unexpected token ' in JSON at position 0
    at JSON.parse (<anonymous>)
    at parse (D:\saqibs\isomorphic\commerce-sdk-isomorphic-main\node_modules\ts-node\dist\index.js:103:45)
    at arg (D:\saqibs\isomorphic\commerce-sdk-isomorphic-main\node_modules\arg\index.js:122:24)
    at main (D:\saqibs\isomorphic\commerce-sdk-isomorphic-main\node_modules\ts-node\dist\bin.js:34:18)
    at Object.<anonymous> (D:\saqibs\isomorphic\commerce-sdk-isomorphic-main\node_modules\ts-node\dist\bin.js:446:5)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
error Command failed with exit code 1.`

**Comment by bredmond-sf** [comment]
Hi @saqibcloudconversion thanks for your report. I'm not able to repro locally, but I think you're seeing this because you have an older version of `ts-node` globally on your system (you can check by running `ts-node --version`). We should be installing the version we need as a devDependency in our project and I've pushed a branch and opened a PR with that change. You can checkout the branch `br/add-ts-node` and repeat the `yarn install` and `yarn run renderTemplates` to confirm.
